# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:03
from __future__ import unicode_literals

import CrawlerSystem.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrawlerSystem', '0002_log_logdefine'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictDefine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe5\xad\x97\xe5\x85\xb8\xe5\x90\x8d')),
                ('key', models.CharField(db_index=True, default=b'825b6ae171454dc7b7829f29f9d4cf80', max_length=50, unique=True, verbose_name=b'\xe6\xa0\x87\xe8\xaf\x86\xe5\x90\x8d')),
                ('_dict', models.TextField(default=b'(d.', verbose_name=b'\xe5\xad\x98\xe9\x94\xae\xe5\x80\xbc')),
                ('group', models.CharField(default=b'', max_length=50, verbose_name=b'\xe7\xbb\x84')),
                ('type', models.IntegerField(choices=[(0, b'\xe5\xad\x97\xe5\x85\xb8'), (1, b'\xe6\x95\xb0\xe6\x8d\xae\xe8\xa1\xa8'), (2, b'\xe6\x96\x87\xe4\xbb\xb6'), (3, b'\xe7\x9b\xae\xe5\xbd\x95')], default=0, verbose_name=b'\xe5\xad\x97\xe5\x85\xb8\xe7\x9a\x84\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('remark', models.CharField(max_length=400, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
            ],
            options={
                'db_table': 'def_dict',
            },
            bases=(models.Model, CrawlerSystem.models.base.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='FieldDefine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.IntegerField(default=0)),
                ('field_type', models.CharField(max_length=20)),
                ('field_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('field_format', models.CharField(max_length=100)),
                ('create_index', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'def_field',
            },
            bases=(models.Model, CrawlerSystem.models.base.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='UserDefinedMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField(max_length=8)),
                ('defined_menu', models.TextField(max_length=1000, verbose_name='\u7528\u6237\u5b9a\u4e49\u7684\u83dc\u5355\u9879')),
                ('map_menu', models.TextField(max_length=1000, verbose_name='\u7cfb\u7edf\u83dc\u5355\u7684\u6620\u5c04')),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'custom_menu',
            },
        ),
        migrations.CreateModel(
            name='ValueDefine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.IntegerField()),
                ('value_id', models.IntegerField()),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'def_value',
            },
            bases=(models.Model, CrawlerSystem.models.base.BaseModelMixin),
        ),
    ]
