# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrawlerSystem', '0003_dictdefine_fielddefine_userdefinedmenu_valuedefine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictdefine',
            name='key',
            field=models.CharField(db_index=True, default=b'f8bea1827ba04e3fb8ce2ef7f16dde0c', max_length=50, unique=True, verbose_name=b'\xe6\xa0\x87\xe8\xaf\x86\xe5\x90\x8d'),
        ),
    ]
